sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t yassir2s/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true yassir2s/react-test npm run test

after_success:
  - docker build -t yassir2s/multi-client ./client
  - docker build -t yassir2s/multi-nginx ./nginx
  - docker build -t yassir2s/multi-server ./server
  - docker build -t yassir2s/multi-worker ./worker
  #Log in the docker CLI
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
  # push images to docker hub
  - docker push yassir2s/multi-client
  - docker push yassir2s/multi-nginx
  - docker push yassir2s/multi-server
  - docker push yassir2s/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "multi-ocker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-west-1-023264199759"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
